# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

version = 1

[[annotations]]
path = [
 "NOTICE",
 "mix.lock"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "CC0-1.0"

# Make sure all generated code doesn't come with licensing obligations
[[annotations]]
path = [
 "templates/new/**"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "CC0-1.0"
