version = 1

[[annotations]]
path = [
 ".circleci/config.yml",
 ".credo.exs",
 ".dialyzer_ignore.exs",
 ".formatter.exs",
 ".github/dependabot.yml",
 ".gitignore",
 "CHANGELOG.md",
 "NOTICE",
 "RELEASE.md",
 "REUSE.toml",
 "mix.exs",
 "mix.lock"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = [
 "README.md"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2018 Frank Hunleth"
SPDX-License-Identifier = "CC-BY-4.0"

# Make sure all generated code doesn't come with licensing obligations
[[annotations]]
path = [
 "templates/new/mix.exs",
 "templates/new/test/app_name_test.exs",
 "templates/new/test/test_helper.exs",
 "templates/new/config/host.exs",
 "templates/new/config/config.exs",
 "templates/new/config/target.exs",
 "templates/new/README.md",
 "templates/new/rel/vm.args.eex",
 "templates/new/.gitignore",
 "templates/new/lib/app_name/application.ex",
 "templates/new/lib/app_name.ex",
 "templates/new/rootfs_overlay/etc/iex.exs",
 "templates/new/.formatter.exs",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "CC0-1.0"


